### ISSUE TITLE
Please help me, need simple example of animation

### ISSUE THREAD

**Issue by Rombersoft** [zwcloud/CairoSharp#6]
I've found it but on gtk+. I need on Gtk#

**Comment by zwcloud** [comment]
Hi, I'm glad to help but how was the animation implemented with gtk+? Any links to that?

**Comment by Rombersoft** [comment]
Implemented with GTK#. You've created and support project which does not have documentation

**Comment by zwcloud** [comment]
Where is the code of the animation example in GTK#? This CairoSharp is not an official GTK# project.
I'm not quite familiar with GTK#.

**Comment by Rombersoft** [comment]
Yes but CairoSharp without GTK# by itself does not work. 
There are many examples of animation for Cairo on Native GTK+ but not the same examples on GTK#. I'm disapointed. Such greate framework does not have documentation.

**Comment by zwcloud** [comment]
> CairoSharp without GTK# by itself does not work.

False. It does work. See [the demos](https://github.com/zwcloud/CairoSharp/tree/master/demos).

I thought you can give me some links to the source code of animation examples. Since you didn't, I will  find those examples of animation for Cario on GTK+ myself, and rewrite them with CarioSharp.

Nothing is impossible. So just wait a moment, please.

**Comment by Rombersoft** [comment]
You can pay attention to examples here https://www.cairographics.org/examples/
They are written on C++ and it would be cool to rewrite them on C#

**Comment by Rombersoft** [comment]
[Simple_GTK.tar.gz](https://github.com/zwcloud/CairoSharp/files/2151773/Simple_GTK.tar.gz)

I've already done some example but as for me animation moves twinkled. I want that animation was  moved smoothly. I'm interested does exist way to draw syncronously with graphic card posibilty. In order to not set interval but interval was set automaticaly as openGL do it? forexample. So I think that at the moment animation moves twinkled because my interval is asincronous with graphic card posibility. 
I like animation here https://www.getlazarus.org/forums/viewtopic.php?f=18&t=40 but here it is not c# although this link I coppied on https://www.cairographics.org/examples/

**Comment by zwcloud** [comment]
> I've already done some example but as for me animation moves twinkled

You will need to do a double-buffered rendering, which I will use in the new animation demos.

**Comment by Rombersoft** [comment]
Yes I know but DoubleBuffered property is obsolete. Give me example.

**Comment by zwcloud** [comment]
Added an animation example in [demos/Windows/WinFormDemo](https://github.com/zwcloud/CairoSharp/blob/c2c3a542eb60da1b94d5f48505e226fae4987400/demos/Windows/WinFormDemo/Form1.cs#L79) at commit c2c3a542eb60da1b94d5f48505e226fae4987400.

The idea is to draw on a `ImageSurface` then paint the `ImageSurface` to the `Win32Surface` instead of directly drawing on the `Win32Surface`. I think it also applies to GTK#. (But I don't know whether CairoSharp can work with GTK#.)

**Comment by Rombersoft** [comment]
Hm, it's for Windows but I need for Linux

**Comment by Rombersoft** [comment]
Was you here? https://www.cairographics.org/examples/

**Comment by zwcloud** [comment]
I have already told you how to use double buffer on WinForm. Please implement it by yourself on GTK#.

**Comment by Rombersoft** [comment]
I know DoubleBuffered in Windows because I did it 5 years. And I've tried
to repeat something with GTK # but I did not notice difference between with
DoubleBuffered and without it

Нд, 1 лип. 2018 р., 15:31 користувач Zou Wei <notifications@github.com>
пише:

**Comment by zwcloud** [comment]
Please [ask the developers of GTK#](https://github.com/mono/gtk-sharp/issues).

Some linux demo projects of CarioSharp will be added when I have time and want to: I will not use GTK#.
